name: Terragrunt Apply

on:
  push:
    branches:
      - master  # Replace with your main branch name if different

jobs:
  terragrunt_apply:
    runs-on: ubuntu-latest  # Use the appropriate runner for your needs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terragrunt fmt check
      run: terragrunt hclfmt --terragrunt-check

    - name: Terraform fmt check
      working-directory: modules/infra
      run: terraform fmt

    - name: Merge to main branch
      run: |
        git config user.name "AiymanKhan786"
        git config user.email "aiymankhan786@gmail.com"
        git fetch
        git merge origin/main

    - name: Terraform Apply - dev
      working-directory: live/dev/us-west-2
      run: terragrunt apply --terragrunt-working-dir=infra

    - name: Terraform Apply - qa
      working-directory: live/qa/us-west-2
      run: terragrunt apply --terragrunt-working-dir=infra

    - name: Terraform Apply - prod
      working-directory: live/prod/us-west-2
      run: terragrunt apply --terragrunt-working-dir=infra
